from time import sleep
from pygame import mixer

friend = 0
alist = ["a", "A"]
blist = ["B", "b"]
clist = ["C", "c"]
dlist = ["d", "D"]

#hello world eindopdracht
#speelt af in een pokemon wereld
#trainer name and Eevee name can be chosen
while True: 
    print("^Hello, i am professor Goei and welcome to the world of pokemon^")
    sleep(.5)
    print("^What is your name pokemon trainer?^")
    name = input()
    print("^Hello " + name + "^")
    print("^What is your Eevees name?^")
    Eevee = input()
    print("^You and " + Eevee + " are no longer safe in Saffron city!^")
    sleep(1)
    print("^There is a pokemon war going on right this second and i advice you to go to lavender town^")
    sleep(1)
    print("^Lavender town is taking people in at the moment^")
    sleep(1)
    print("^Goodluck on your journey...^")
    sleep(2)
    print("*you and Eevee are going on a journey to Lavender town*")
    sleep(1)
    print("*you come across a path that splits in 2")
    sleep(1)
    print('The left path looks dark and ominoous, the right path looks safe and well lit')
    sleep(1)
    print("Which path wil you chose?")
    sleep(1)
    print("Left (dark and ominous) or right (safe and bright)")
    answer = input()
    if answer == "left":
            #safe choice, story continues
            print("You and eevee go on the left path")
            sleep(.5)
            print("you walk along the path casious...")
            sleep(2)
            print("You hear something rumble in the distance")
            sleep(.5)
            print("The bushes next to you start shaking, you and " + name + " start preparing for battle")
            sleep(1)
            print("Something jumps out of the bush!")
            sleep(1)
            print("Its a bunnelby!")
            sleep(1)
            print("Eevee and bunnelby start sniffing eachother...")
            sleep(1)
            print("*" + Eevee + " made a friend!*")
            sleep(1)
            print("Achievement unlocked: Friends")
            friend = friend + 1
            print("Your eevee's love has increased by 10")
            love = love + 10
            # continue story
            sleep(1)
            print("You and " + Eevee + " come across another split path")
            sleep(1)
            print("The paths are labelled")
            print("a. Safe route lavender town    b. Short route lavender town    c. Unicorn forest")
            sleep(.5)
            print("which path will you choose? a/b/c")
            answer2 = input()
            if answer2 in alist:
                print("You go on the safe path")
                sleep(1)
                print("You and " + eevee + " are walking along the path when you come across a snorlax...")
                sleep(1)
                print("The Snorlax seems agitated...")
                sleep(1)
                print("Be carefull... ")
                sleep(1)
                print("*Your Eevee walks over to the Snorlax and gives it a hug!")
                sleep(1)
                print("Snorlax seems happier, i guess it was just having a bad day")
                sleep(2)
                print("Snorlax and Eevee become friends, + 1 friend, + 10 love")
                friend = friend + 1
                print("You and " + eevee + " continue your journey to lavender town...")
                sleep(2)
                #story continues to all the eevee endings
                #your eevee will gain love
                print("You come across another split...")
                sleep(1)
                print("The paths are labelled yes and no?? Which idiot thought of that...")
                sleep(1)
                print("The path that is labelled yes looks quite safe and the path that is labelled no is very closed off, you cannot see what is going on on path *no*")
                sleep(3)
                print("Which path are you choosing? yes/no")
                answer5 = input()
                if answer5 == "yes":
                    print("You go onto path yes...")
                    #path yes = death
                if answer5 == "no":
                    print("You go on path no....")
                    sleep(1)
                    #you survive
                    print("It looks a bit unsafe.....")
                    sleep(1)
                    print("Are you sure you wanna go on this path? yes/no")
                    answer6 = input()
                    if answer6 == "yes":
                        #you dont die
                        sleep(1)
                        print("You continue walking on this path...")
                        sleep(1)
                        print("A wild Bulbasoar!")
                        sleep(1)
                        print("Bulbasoar challenges you...")
                        sleep(1)
                        print("Bulbasoar used Tackle")
                        sleep(.5)
                        print("Eevee dodged")
                        sleep(.5)
                        print("Eevee used quick attack")
                        sleep(.5)
                        print("critical hit!")
                        sleep(0.5)
                        print("Bulbasoar fainted...")
                        sleep(1)
                        print("You and eevee continue walking to lavender town")
                        sleep(1)
                        #play lavender town music
                        print("Lavender town reached")
                        sleep(1)
                        #doors question
                        print("You and eevee are walking around town in hopes to meet some people...")
                        sleep(1)
                        print("The streets are empty")
                        sleep(0.5)
                        print("What will you do?")
                        sleep(0.5)
                        print("A. knock on door yellow     B. knock on door pink    C. knock on door green    d. knock on door blue")
                        answer7 = input()
                        if answer7 in alist:
                            #Jolteon of Flareon evolution
                            print("You knock on the yellow door...")
                            sleep(2)
                            print("A man opens the door, it's pokemon trainer Sparky!")
                            sleep(1)
                            print("^Oh hello! You must be the new trainer in town everyone is talking about! " + name + " right?^")
                            sleep(1)
                            print("^If you like i could show you around town?^")
                            sleep(2)
                            print("^Great! where do you wanna go first?^")
                            sleep(1)
                            print("^We can go to one of my favorite place, the racetrack!^")
                            sleep(1)
                            print("^Or if you want we can go to the towns bonfire!^")
                            sleep(1)
                            print("A. racetracks    B. bonfire")
                            answer8 = input()
                            if answer8 in alist:
                                #jolteon evolution
                                print("^Lets go to the racetracksssssss!!!!!^")
                                sleep(1)
                                print("You arrive at the racetracks. There are some cars on the tracks")
                                sleep(1)
                                print("Sparky shows you the car he races withh from time to time")
                                sleep(1)
                                print("You and " + Eevee + " meet some racers")
                                sleep(1)
                                print("You and your eevee have a great time")
                                sleep(1)
                                print("Eevee gains +10 love!")
                                sleep(1)
                                print("Oh? Your eevee is evolving!")
                                sleep(2)
                                print("Your eevee has evolved into a Jolteon!")
                                sleep(1)
                                print(Eevee + " must've loved the racetracks a lot for it to evolve!")
                                sleep(3)
                                print("in the future")
                                sleep(1)
                                print("You and " + Eevee + " have made friends with the people from the tracks and visit it a lot")
                                sleep(2)
                                print("You and Jolteon have settled in well in lavender town")
                                sleep(3)
                                print("Congratulations! You got the Jolteon ending!")
                                sleep(1)
                                print("You can play again if you want to try and get a different ending")
                                sleep(1)
                                print("Good job " + name)
                            if answer8 in blist:
                                #flareon evolution
                                print("^Great! Lets go to the towns bonfire! Maybe you can meet some people!^")
                                sleep(1)
                                print("^This towns bonfires are so fun, everyone comes to it^")
                                sleep(1)
                                print("^Maybe you can meet some of the townspeople and get to know them^")
                                sleep(1)
                                print("^That way you will have some friends here^")
                                sleep(1)
                                print("-You arrive at the towns bonfire with sparky and " + Eevee)
                                sleep(1)
                                print("Sparky introduces you to some townspeople")
                                sleep(1)
                                print("You make some friends, while eevee plays near the fire")
                                sleep(1)
                                print("You notice your eevee is playing with charmeleon and he is showing her some fire tricks")
                                sleep(2)
                                print("Eevee gains +10 love and +10 arsonist")
                                sleep(1)
                                print("Oh? Eevee is evolving!")
                                sleep(2)
                                print("Eevee has evolved into a Flareon!")
                                sleep(1)
                                print("Guess she really liked the fire huh")
                                sleep(1)
                                print("-some time later-")
                                sleep(1)
                                print("You and " + Eevee + " have settled in nicely in lavender town")
                                sleep(1)
                                print("You made friends at the bonfire and Flareon hangs out with some other fire types")
                                sleep(2)
                                print("Congratulations! You got the Flareon ending!")
                                sleep(1)
                                print("You can play again to get different endings!")
                                sleep(1)
                                print("Im proud of you " + name)
                        if answer7 in blist:
                            #Espeon or Sylveon evolution
                            print("You knock on the pink door...")
                            sleep(2)
                            print("A man opens the door, it's doctor Heart!")
                            sleep(1)
                            print("^Oh hello! You must be the new trainer in town everyone is talking about! " + name + " right?^")
                            sleep(1)
                            print("^If you like i could show you around town?^")
                            sleep(2)
                            print("^Great! where do you wanna go first?^")
                            sleep(1)
                            print("^We can go to a fortune teller or the local daycare?^")
                            sleep(1)
                            print("A. fortune teller     B. daycare")
                            answer9 = input()
                            if answer9 in alist:
                                #Espeon evolution
                                print("^Great, my wife is actually the fortune teller, i love her!^")
                                sleep(1)
                                print("You and Dr. Heart go to his wife")
                            if answer9 in blist:
                                #sylveon evolution
                                print("^Really? Usually nobody wants to go to the daycare, i personally love kids^")
                                sleep(1)
                        if answer7 in clist:
                            #Leafeon or Umbreon evolution
                            print("You knock on the green door...")
                            sleep(2)
                            print("A woman opens the door, it's trainer Gardenia!")
                            sleep(1)
                            print("^Oh hello! You must be the new trainer in town everyone is talking about! " + name + " right?^")
                            sleep(1)
                            print("^If you like i could show you around town?^")
                            sleep(2)
                            print("^Great! where do you wanna go first?^")
                            sleep(1)
                            print("^Personally my favorite place is the botanical garden, but some people prefer the disco nearby^")
                            sleep(1)
                            print("A. botanical garden    B. disco")
                            answer10 = input()
                            if answer10 in alist:
                                #leafeon evolution
                                print("^Awesome! Lets go!^")
                                sleep(1)
                            if answer10 in blist:
                                #Umbreon
                                print("^Alright! It is a great place to meet people!^")
                                sleep(1)
                        if answer7 in dlist:
                            #Vaporeon or Glaceon evolution
                            print("You knock on the blue door...")
                            sleep(2)
                            print("A girl opens the door, it's aqua!")
                            sleep(1)
                            print("^Oh hello! You must be the new trainer in town everyone is talking about! " + name + " right?^")
                            sleep(1)
                            print("^If you like i could show you around town?^")
                            sleep(2)
                            print("^Great! where do you wanna go first?^")
                            sleep(1)
                            print("^I love the waterpark and the ice rink! They are the best places in town!^")
                            sleep(1)
                            print("A. waterpark     B. ice rink")
                            answer11 = input()
                            if answer11 in alist:
                                #vaporeon evolution
                                print("^YAY! I havent been there in such a long time!^")
                                sleep(1)
                            if answer11 in blist:
                                #glaceon evoluton
                                print("^Good choice, its such a lovely place!^")
                                sleep(1)
                    if answer6 == "no":
                        #you die
                        sleep(1)
                        print("You go back and go on the safe looking path instead...")
                        sleep(1)
                        print("There is a nice looking Tyranitar there")
                        sleep(1)
                        print("OH!" + sleep(1) + " It wants to battle...")
                        sleep(1)
                        print("The tyranitar uses CRUNCH")
                        sleep(0.5)
                        print("CRITICAL HIT!")
                        sleep(0.5)
                        print("Your Eevee fainted")
                        sleep(1)
                        print("You died...")
                        sleep(1)
                        print("You got the Eevee battle ending!")
                        sleep(1)
                        print("You can play again to try and get a different ending")
                        sleep(1)
            if answer2 in blist:
                print("You go on the short path")
                sleep(1)
                print("The path is difficult and your eevee gets very stressed")
                sleep(1)
                print("Eevee gets stuck and you free her")
                sleep(1)
                print("*your eevee didnt gain love*")
                sleep(1)
                print("-you arrive in lavender town-")
                sleep(1)
                print("After a long and hard journey you and eevee can finally rest on a bench")
                sleep(2)
                print("A townsperson walks up to you...")
                sleep(1)
                print("^Hello my name is Lila^")
                sleep(1)
                print("^I saw your Eevee over there and i was wondering if she would like to play with my pikachu?^")
                sleep(1)
                print("Do you want " + Eevee + " to play with pikachu? yes/no")
                answer3 = input()
                if answer3 == "yes":    
                    print("^Great!^")
                    sleep(1)
                    print("Eevee and pikachu have a great time")
                    sleep(1)
                    print(Eevee + " has made a friend!")
                    sleep(1)
                    print("Eevee gained +10 love")
                    sleep(1)
                    print("^It seems like pikachu and Eevee get along great!^")
                    print("^would you like to go to the towns bonfire with me an pikachu?")
                    print("A. accept the invitation    B. Ask her out on a walk in the moonlight instead  a/b")
                    answer4 = input()
                    if answer4 in alist:
                        print("^Lovely! I cant wait for you to meet all the others!^")
                        sleep(1)
                        print("You and Lila go to the towns bonfire and she introduces you to all the people there")
                        sleep(1)
                        print("Your Eevee is getting along great with all the other pokemon!")
                        sleep(.5)
                        print(Eevee + " has made a bunch of friends!")
                        sleep(1)
                        print("*+10 love*")
                        sleep(1)
                        print("Oh? Eevee is evolving!")
                        sleep(1)
                        print("Eevee has evolved into a Sylveon!")
                        sleep(1)
                        print("Achievement unlocked: Sylveon")
                        sleep(1)
                        print("She must have been so filled with love from the bonfire she evolved into a fairy type!")
                        sleep(2)
                        print("some time later...")
                        sleep(1)
                        print('You and ' + Eevee + " made a bunch of friends!")
                        sleep(1)
                        print("You two fit right in with the lavender town people")
                        sleep(1)
                        print("Congratulations! You have made it to the Sylveon bonfire ending!")
                        sleep(1)
                        print("I am so proud of you " + name)
                        sleep(2)
                    if answer4 in blist:
                        #pikachu and eevee kiss, eevee turns into umbreon
                        print("^Oh! uhmm sure, i would love too! :o ^")
                        sleep(1)
                        print("You and Lila go on a walk in the moonlight...")
                        sleep(2)
                        print("Pikachu and Eevee are playing together")
                        sleep(1)
                        print("oh? Pikachu kisses Eevee, +10 love")
                        sleep(1)
                        print("Eevee is filled with love under the moon")
                        sleep(1)
                        print(Eevee + " is evolving!")
                        sleep(.5)
                        print("Eevee has evolved into an umbreon!")
                        sleep(1)
                        print("Achievement unlocked: Umbreon")
                        sleep(1)
                        print("-some time later-")
                        sleep(1)
                        print("You and " + Eevee + " have settled in into lavender town!")
                        sleep(1)
                        print(Eevee + " and Pikachu got married")
                        sleep(3)
                        print("Congratulations! You got the umbreon love ending")
                        sleep(1)
                        print("I am proud of you " + name)
                        sleep(2)
                if answer == "no":
                        print("^Thats a shame :(")
                        sleep(1)
                        print("^I guess i'll talk to you some other time...")
                        sleep(2)
                        print("You and Eevee dont make any friends after that and live a lonely life in lavender town")
                        sleep(3)
                        print("You made it to the end!")
                        sleep(1)
                        print("You got the lonely ending...")
                        sleep(2)
            if answer2 in clist:
                #you will die
                print("You go into the unicorn forest")
                sleep(1)
                print("It doesnt look as peaceful as you expected...")
                sleep(1)
                #a unicorn will kill you
                print("Something is rumbling in the bushes...")
                sleep(2)
                print("A unicorn comes running out of the bushes and hit you")
                sleep(.5)
                print("Poor thing must have been scared, at least its okay now")
                print("You on the other hand...")
                sleep(1)
                print("You are fatally injured and bleeding out")
                sleep(1)
                print("You died, your body couldnt hold on and gave out because of your injuries")
                sleep(1)
                print("Maybe going into a unicorn forest wasn't the smartest bet...")
                sleep(2)
    if answer == "right":
            #bad choice, you die
            #there is a cliff and you slip and die
            print("You go on the right safe path...")
            sleep(1)
            print("You look at the beautiful view of the cliff and river to your right")
            sleep(2)
            print("Suddenly you slip and fall")
            sleep(1)
            print("You fell off the cliff, you have died")
            sleep(2)
    else:
         print("Sorry thats not a viable answer, try again")
         sleep(1)
    while True:
        
        
        #put other achievements here, achievement for every evolution
        sleep(2)
        print("Would you like to play again? yes/no")
        answer0 = input()
        if answer0 == "yes":
            print("goodluck!")
            sleep(2)
        if answer == "no":
            print("goodbye!")
            break
        else: 
            print("Sorry thats not a valid answer, try again!")